### PR TITLE
build: Use pycodestyle rather than setuptools_pep8

### PR DESCRIPTION
**Pull request by pwithnall**
The latter is unmaintained and was complicating setup.

Signed-off-by: Philip Withnall <pwithnall@endlessos.org>

Fixes: #18

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Thanks!

Would you be able to make a new release with these changes? I'd like to package this for Arch Linux as a dependency for something else.

**Comment by pwithnall** [comment]
https://pypi.org/manage/project/dbus-deviation/release/0.6.1/

**Comment by eli-schwartz** [comment]
Thanks!

https://archlinux.org/packages/community/any/python-dbus-deviation/

**Comment by pwithnall** [comment]
Thanks. Do people actually use it?

(Would they be interested in developing it more actively than I do??)

**Comment by eli-schwartz** [comment]
It's currently used by https://github.com/hotdoc/hotdoc

**Comment by eli-schwartz** [comment]
I have no idea if @MathieuDuponchelle has an interest in helping to develop this, but... ping is free.

**Comment by MathieuDuponchelle** [comment]
I am not aware of any active user of hotdoc's dbus extension tbh, I simply keep it functional in case some project does want to use it

**Pull request merged**
