### PR TITLE
dbusapi: Parse comments associated with dbus nodes

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
No regressions with pep8 or pylint.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
I have fixed the various issues related with my code, I don't see how this last error could be related to be honest.

**Comment by MathieuDuponchelle** [comment]
So to summarize, the proposed design is:

If an xml comment is immediately above an interface / method / property / signal, it will be picked as being the documentation for that element, *even if* the name doesn't match, as dbusapi will not parse the comments.

However if this element contains either:

{http://telepathy.freedesktop.org/wiki/DbusSpec#extensions-v0}docstring
or
{http://www.freedesktop.org/dbus/1.0/doc.dtd}doc

Then they will be picked over the xml comment.

**Comment by pwithnall** [comment]
Waiting for feedback from Simon McVittie about what documentation format we want to recommend for D-Bus introspection XML files, as that affects this patch, as per Mathieu’s most recent comment. Apart from that, the patch needs the following changes:
 * Rename from `Commentable` to `Documentable`
 * Expose the `docstring` and `doc` elements as documentation if they are present
 * Add more tests (for `docstring` vs `doc` vs `comment`, whitespace formatting, documentation on each node type, etc.)
 * Fix the landscape.io code smells (see https://landscape.io/diff/212394)
 * Support `Documentable` on `ast.Argument` too

**Comment by MathieuDuponchelle** [comment]
The landscape link errors out FWIW, must be more than code smells in there :P

**Comment by MathieuDuponchelle** [comment]
I addressed all the issues raised, and fixed up the AST reimplementation patches.

**Comment by MathieuDuponchelle** [comment]
```
5 files changed, 539 insertions(+), 953 deletions(-)
```

and an improved coverage with two thirds of the amount of tests shows this was really needed IMHO

**Comment by pwithnall** [comment]
Overall, this looks like a good improvement, thanks — the remaining issues are fairly minor.

> improved coverage with two thirds of the amount of tests shows this was really needed IMHO

I wouldn’t say it was ‘really needed’ since the original code worked fine. However, it does make it more maintainable in future.

**Comment by MathieuDuponchelle** [comment]
I addressed the remaining issues you had, really hoping you can take it on from there now, I suppose you can do the fixup on your end if you're finally happy with the state of the code.

**Comment by pwithnall** [comment]
Various problems fixed, the API breakages fixed (at the cost of a new `FIXME`), and some more quoting added to `Annotation.pretty_name`, but more work still needs to be done on the pretty names. Building English-language strings by prepending and appending things is generally infeasible.

**Pull request closed without merging**
