### PR TITLE
Moved Log() to a separate file to allow reuse for other parts of dbusapi.

### PR DESCRIPTION
**Pull request by zayfod**

### CODE REVIEW

**Comment by pwithnall** [comment]
Looks good to me, but depends on the `Log.clear()` changes which need merging first.

**Comment by zayfod** [comment]
Ah, come on! These are independent. :)

**Comment by pwithnall** [comment]
Hang on, I’ll resolve and merge myself.

**Comment by zayfod** [comment]
OK. I appreciate it. :)

**Comment by pwithnall** [comment]
Rebased and merged:
8761a94 dbusapi: Move Log() to a separate file to allow reuse

**Comment by MathieuDuponchelle** [comment]
Nice :) FWIW as this class is strictly used to log issues, it may be nicer to call it "Diagnostics" and provide __getitem__ accessors for bonus convenience.

**Pull request closed without merging**
